# Generated by Django 5.0 on 2023-12-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
