# Generated by Django 5.0 on 2023-12-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productcomment_checkbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='email',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
